// terms.js
// 学年(grade): 1/2/3
// 分野(field): life / chem / phys / earth
// term: 用語
// hint: 用語クイズ用の短い説明（ここは“あなたの言葉”でOK）

const TERMS = [
  // ===== 1年 生命 =====
  { grade: 1, field: "life", term: "細胞", hint: "生物の体をつくる最小の単位。" },
  { grade: 1, field: "life", term: "核", hint: "細胞の中で、遺伝に関わる情報を含む部分。" },
  { grade: 1, field: "life", term: "細胞膜", hint: "細胞の外側を包み、物質の出入りを調節する。" },
  { grade: 1, field: "life", term: "葉緑体", hint: "植物細胞に多く、光合成に関わるつくり。" },
  { grade: 1, field: "life", term: "顕微鏡", hint: "小さなものを大きく見えるようにする器具。" },
  { grade: 1, field: "life", term: "ルーペ", hint: "近くの物を拡大して観察する道具。" },
  { grade: 1, field: "life", term: "双眼実体顕微鏡", hint: "立体的に観察できる顕微鏡。" },
  { grade: 1, field: "life", term: "被子植物", hint: "花を咲かせ、種子が果実に包まれる植物。" },
  { grade: 1, field: "life", term: "裸子植物", hint: "種子がむき出し（果実に包まれない）の植物。" },
  { grade: 1, field: "life", term: "子葉", hint: "発芽のときに最初に出る葉。" },
  { grade: 1, field: "life", term: "胚", hint: "種子の中の、成長して植物になる部分。" },
  { grade: 1, field: "life", term: "花粉", hint: "雄しべでつくられ、受粉に関わる粒。" },
  { grade: 1, field: "life", term: "受粉", hint: "花粉がめしべの先に付くこと。" },
  { grade: 1, field: "life", term: "受精", hint: "精細胞と卵細胞が合体して新しい細胞になること。" },
  { grade: 1, field: "life", term: "蒸散", hint: "植物が葉などから水を水蒸気として出すこと。" },
  { grade: 1, field: "life", term: "根毛", hint: "根の表面にあり、水や養分を吸収しやすくする。" },
  { grade: 1, field: "life", term: "維管束", hint: "水や養分を運ぶ管が集まったつくり。" },
  { grade: 1, field: "life", term: "道管", hint: "根から吸い上げた水を運ぶ管。" },
  { grade: 1, field: "life", term: "師管", hint: "葉でつくられた養分を運ぶ管。" },
  { grade: 1, field: "life", term: "気孔", hint: "葉の表面にある穴で、気体の出入りを行う。" },
  { grade: 1, field: "life", term: "デンプン", hint: "植物がつくる代表的な養分で、ヨウ素液で青紫色。" },
  { grade: 1, field: "life", term: "脊椎動物", hint: "背骨がある動物の仲間。" },
  { grade: 1, field: "life", term: "無脊椎動物", hint: "背骨がない動物の仲間。" },
  { grade: 1, field: "life", term: "哺乳類", hint: "体毛があり、子を母乳で育てる仲間。" },
  { grade: 1, field: "life", term: "鳥類", hint: "体が羽毛でおおわれ、卵を産む仲間。" },
  { grade: 1, field: "life", term: "魚類", hint: "えらで呼吸し、水中で生活する仲間。" },
  { grade: 1, field: "life", term: "両生類", hint: "水中と陸上の両方で生活する特徴がある仲間。" },
  { grade: 1, field: "life", term: "は虫類", hint: "体表がうろこでおおわれ、陸上生活に適した仲間。" },

  // ===== 1年 物質（chem扱い） =====
  { grade: 1, field: "chem", term: "物質", hint: "形や体積をもつ“もの”の材料。" },
  { grade: 1, field: "chem", term: "金属", hint: "電気を通しやすく、みがくと光る性質があることが多い。" },
  { grade: 1, field: "chem", term: "密度", hint: "同じ体積あたりの質量。物質の見分けに使える。" },
  { grade: 1, field: "chem", term: "溶質", hint: "溶ける側の物質。" },
  { grade: 1, field: "chem", term: "溶媒", hint: "溶かす側の液体（例：水）。" },
  { grade: 1, field: "chem", term: "溶液", hint: "溶質が溶媒に溶けた液体。" },
  { grade: 1, field: "chem", term: "水溶液", hint: "溶媒が水の溶液。" },
  { grade: 1, field: "chem", term: "溶解度", hint: "一定温度で一定量の水に溶ける溶質の最大量。" },
  { grade: 1, field: "chem", term: "飽和水溶液", hint: "それ以上溶けない状態の水溶液。" },
  { grade: 1, field: "chem", term: "再結晶", hint: "温度変化を利用して、溶質を結晶として取り出す方法。" },
  { grade: 1, field: "chem", term: "ろ過", hint: "溶けない固体を分ける操作。" },
  { grade: 1, field: "chem", term: "蒸留", hint: "沸点の違いを利用して液体を分ける方法。" },
  { grade: 1, field: "chem", term: "混合物", hint: "2種類以上の物質が混ざったもの。" },
  { grade: 1, field: "chem", term: "純物質", hint: "1種類の物質だけからなるもの。" },
  { grade: 1, field: "chem", term: "融点", hint: "固体が液体になり始める温度。" },
  { grade: 1, field: "chem", term: "沸点", hint: "液体が沸騰し始める温度。" },
  { grade: 1, field: "chem", term: "状態変化", hint: "固体・液体・気体の状態が変わること。" },
  { grade: 1, field: "chem", term: "凝固", hint: "液体が固体になること。" },
  { grade: 1, field: "chem", term: "蒸発", hint: "液体が気体になること（表面から）。" },
  { grade: 1, field: "chem", term: "沸騰", hint: "液体全体から気体が出る変化。" },

  // ===== 1年 エネルギー（phys） =====
  { grade: 1, field: "phys", term: "光の反射", hint: "光が物体に当たり、はね返ること。" },
  { grade: 1, field: "phys", term: "入射角", hint: "入ってくる光と法線がつくる角。" },
  { grade: 1, field: "phys", term: "反射角", hint: "反射した光と法線がつくる角。" },
  { grade: 1, field: "phys", term: "凸レンズ", hint: "中央がふくらみ、光を集めるレンズ。" },
  { grade: 1, field: "phys", term: "焦点", hint: "平行光が集まる点（レンズの場合）。" },
  { grade: 1, field: "phys", term: "実像", hint: "スクリーンに映せる像。" },
  { grade: 1, field: "phys", term: "音", hint: "物体の振動が伝わって感じるもの。" },
  { grade: 1, field: "phys", term: "振幅", hint: "振動のふれの大きさ。" },
  { grade: 1, field: "phys", term: "振動数", hint: "1秒間の振動の回数（Hz）。" },
  { grade: 1, field: "phys", term: "力", hint: "物体の運動のようすを変えるはたらき。" },
  { grade: 1, field: "phys", term: "ばねばかり", hint: "力の大きさを測る器具（N）。" },
  { grade: 1, field: "phys", term: "作用・反作用", hint: "力は必ず対になってはたらく。" },
  { grade: 1, field: "phys", term: "力の合成", hint: "2つ以上の力を1つの力として表すこと。" },
  { grade: 1, field: "phys", term: "力の分解", hint: "1つの力を成分に分けて考えること。" },

  // ===== 1年 地球（earth） =====
  { grade: 1, field: "earth", term: "火山", hint: "地下のマグマが地表に出る現象が起こる場所。" },
  { grade: 1, field: "earth", term: "マグマ", hint: "高温でどろどろの岩石（地下）。" },
  { grade: 1, field: "earth", term: "溶岩", hint: "地表に出たマグマ。" },
  { grade: 1, field: "earth", term: "火山灰", hint: "細かい火山噴出物。" },
  { grade: 1, field: "earth", term: "地震", hint: "地面がゆれる現象。" },
  { grade: 1, field: "earth", term: "震源", hint: "地震が起こり始めた地下の場所。" },
  { grade: 1, field: "earth", term: "震央", hint: "震源の真上の地表の地点。" },
  { grade: 1, field: "earth", term: "P波", hint: "最初に伝わる、たて波のゆれ。" },
  { grade: 1, field: "earth", term: "S波", hint: "あとから伝わる、横波のゆれ。" },
  { grade: 1, field: "earth", term: "地層", hint: "地面の下に重なっている層。" },
  { grade: 1, field: "earth", term: "化石", hint: "昔の生物の体や生活の跡が地層に残ったもの。" },

  // ===== 2年 化学 =====
  { grade: 2, field: "chem", term: "原子", hint: "物質をつくる最小の粒の1つの考え方。" },
  { grade: 2, field: "chem", term: "分子", hint: "原子が結びついた粒。" },
  { grade: 2, field: "chem", term: "化学式", hint: "物質を原子記号で表した式。" },
  { grade: 2, field: "chem", term: "化学反応式", hint: "反応物と生成物を式で表したもの。" },
  { grade: 2, field: "chem", term: "化学変化", hint: "別の物質ができる変化。" },
  { grade: 2, field: "chem", term: "質量保存の法則", hint: "反応の前後で物質全体の質量は変わらない。" },
  { grade: 2, field: "chem", term: "酸化", hint: "物質が酸素と結びつく反応のことが多い。" },
  { grade: 2, field: "chem", term: "還元", hint: "酸化物から酸素がうばわれる変化など。" },
  { grade: 2, field: "chem", term: "熱分解", hint: "加熱して別の物質に分かれる反応。" },
  { grade: 2, field: "chem", term: "電気分解", hint: "電流で分解して別の物質を得る反応。" },

  // ===== 2年 生命 =====
  { grade: 2, field: "life", term: "光合成", hint: "光を受けて二酸化炭素と水から養分をつくるはたらき。" },
  { grade: 2, field: "life", term: "呼吸", hint: "養分を分解してエネルギーを取り出すはたらき。" },
  { grade: 2, field: "life", term: "消化", hint: "食べ物を小さな物質に分解すること。" },
  { grade: 2, field: "life", term: "吸収", hint: "消化された養分が体内に取り込まれること。" },
  { grade: 2, field: "life", term: "血液", hint: "酸素や養分などを運ぶ体液。" },
  { grade: 2, field: "life", term: "心臓", hint: "血液を全身へ送り出すポンプの役割。" },
  { grade: 2, field: "life", term: "肺", hint: "酸素と二酸化炭素を交換する器官。" },
  { grade: 2, field: "life", term: "小腸", hint: "消化と吸収が進む器官。" },
  { grade: 2, field: "life", term: "大腸", hint: "水分を吸収し、便をつくる器官。" },
  { grade: 2, field: "life", term: "感覚器官", hint: "光・音・においなどを感じ取る器官。" },
  { grade: 2, field: "life", term: "刺激と反応", hint: "刺激を受けて体が変化・行動するしくみ。" },

  // ===== 2年 地球（天気） =====
  { grade: 2, field: "earth", term: "気圧", hint: "空気が押す力のはたらき。" },
  { grade: 2, field: "earth", term: "湿度", hint: "空気中の水蒸気の“しめり具合”の割合。" },
  { grade: 2, field: "earth", term: "露点", hint: "空気を冷やして水滴が生じ始める温度。" },
  { grade: 2, field: "earth", term: "飽和水蒸気量", hint: "空気がふくめる水蒸気の最大量（温度で変わる）。" },
  { grade: 2, field: "earth", term: "雲", hint: "小さな水滴や氷の粒が集まったもの。" },
  { grade: 2, field: "earth", term: "前線", hint: "性質の異なる気団が接する境目。" },
  { grade: 2, field: "earth", term: "低気圧", hint: "周りより気圧が低い所。上昇気流が起こりやすい。" },
  { grade: 2, field: "earth", term: "高気圧", hint: "周りより気圧が高い所。下降気流が起こりやすい。" },

  // ===== 2年 物理（電気） =====
  { grade: 2, field: "phys", term: "電流", hint: "電気の流れ。単位はA（アンペア）。" },
  { grade: 2, field: "phys", term: "電圧", hint: "電流を流そうとするはたらき。単位はV（ボルト）。" },
  { grade: 2, field: "phys", term: "抵抗", hint: "電流の流れにくさ。単位はΩ（オーム）。" },
  { grade: 2, field: "phys", term: "オームの法則", hint: "電圧・電流・抵抗の関係（V=IR）。" },
  { grade: 2, field: "phys", term: "直列回路", hint: "電流の通り道が1本の回路。" },
  { grade: 2, field: "phys", term: "並列回路", hint: "電流の通り道が分かれる回路。" },
  { grade: 2, field: "phys", term: "電力", hint: "電気の仕事の速さ。単位はW（ワット）。" },
  { grade: 2, field: "phys", term: "磁界", hint: "磁石の力がはたらく空間。" },
  { grade: 2, field: "phys", term: "電磁誘導", hint: "磁界の変化で電流が生じる現象。" },

  // ===== 3年 生命（遺伝） =====
  { grade: 3, field: "life", term: "無性生殖", hint: "親1個体からふえる。遺伝情報は同じになりやすい。" },
  { grade: 3, field: "life", term: "有性生殖", hint: "卵と精子などが関わってふえる。" },
  { grade: 3, field: "life", term: "減数分裂", hint: "生殖細胞ができるときの特別な細胞分裂。" },
  { grade: 3, field: "life", term: "遺伝", hint: "親の性質が子に受け継がれること。" },
  { grade: 3, field: "life", term: "DNA", hint: "遺伝情報をもつ物質。" },
  { grade: 3, field: "life", term: "染色体", hint: "DNAを含む、遺伝情報のかたまり。" },
  { grade: 3, field: "life", term: "対立形質", hint: "同じ性質のちがい（例：丸い/しわ）。" },
  { grade: 3, field: "life", term: "顕性", hint: "表れやすい性質（優性）。" },
  { grade: 3, field: "life", term: "潜性", hint: "表れにくい性質（劣性）。" },
  { grade: 3, field: "life", term: "分離の法則", hint: "対立形質が次世代に分かれて現れるという規則。" },
  { grade: 3, field: "life", term: "クローン", hint: "遺伝情報が同じ個体（または細胞）をつくること。" },

  // ===== 3年 化学（イオン） =====
  { grade: 3, field: "chem", term: "イオン", hint: "電気を帯びた原子や分子。" },
  { grade: 3, field: "chem", term: "陽イオン", hint: "＋の電気を帯びたイオン。" },
  { grade: 3, field: "chem", term: "陰イオン", hint: "−の電気を帯びたイオン。" },
  { grade: 3, field: "chem", term: "電解質", hint: "水溶液が電気を通す物質。" },
  { grade: 3, field: "chem", term: "非電解質", hint: "水溶液が電気を通しにくい物質。" },
  { grade: 3, field: "chem", term: "酸", hint: "水溶液中で水素イオンを出す性質（中学的定義）。" },
  { grade: 3, field: "chem", term: "アルカリ", hint: "水溶液中で水酸化物イオンを出す性質（中学的定義）。" },
  { grade: 3, field: "chem", term: "中和", hint: "酸とアルカリが反応して性質が打ち消し合うこと。" },
  { grade: 3, field: "chem", term: "指示薬", hint: "液性によって色が変わる薬品。" },
  { grade: 3, field: "chem", term: "水素イオン", hint: "酸の性質に関わる＋のイオン。" },
  { grade: 3, field: "chem", term: "水酸化物イオン", hint: "アルカリの性質に関わる−のイオン。" },
  { grade: 3, field: "chem", term: "電池", hint: "化学変化で電流を取り出すしくみ。" },

  // ===== 3年 物理（運動とエネルギー） =====
  { grade: 3, field: "phys", term: "仕事", hint: "力が物体を動かしたときの量（力×距離）。" },
  { grade: 3, field: "phys", term: "仕事率", hint: "一定時間あたりの仕事（速さ）。" },
  { grade: 3, field: "phys", term: "運動エネルギー", hint: "運動している物体がもつエネルギー。" },
  { grade: 3, field: "phys", term: "位置エネルギー", hint: "高い所など、位置によってもつエネルギー。" },
  { grade: 3, field: "phys", term: "エネルギー保存", hint: "形を変えてもエネルギー全体は一定とみなす考え。" },
  { grade: 3, field: "phys", term: "慣性", hint: "運動の状態を保とうとする性質。" },
  { grade: 3, field: "phys", term: "速さ", hint: "一定時間に進む距離。" },
  { grade: 3, field: "phys", term: "加速度", hint: "速さの変化の割合（中学では感覚的に扱うことが多い）。" },
  { grade: 3, field: "phys", term: "水圧", hint: "水が押す力。深いほど大きい。" },
  { grade: 3, field: "phys", term: "浮力", hint: "水中で物体が受ける上向きの力。" },

  // ===== 3年 地球（宇宙） =====
  { grade: 3, field: "earth", term: "日周運動", hint: "1日の中で天体が動いて見えるようす。" },
  { grade: 3, field: "earth", term: "年周運動", hint: "1年の中で星座などが変化して見えるようす。" },
  { grade: 3, field: "earth", term: "地軸", hint: "地球が自転するときの回転の軸。" },
  { grade: 3, field: "earth", term: "自転", hint: "地球が1日に1回回転すること。" },
  { grade: 3, field: "earth", term: "公転", hint: "地球が太陽の周りを1年で回ること。" },
  { grade: 3, field: "earth", term: "月の満ち欠け", hint: "太陽光の当たり方で、月の見え方が変わること。" },
  { grade: 3, field: "earth", term: "太陽系", hint: "太陽とその周りを回る天体の集まり。" },
  { grade: 3, field: "earth", term: "銀河系", hint: "多数の恒星が集まった“天の川銀河”のこと。" },
];
