// terms.js
// 学年(grade): 1/2/3
// 分野(field): life / chem / phys / earth
// term: 用語
// hint: 用語クイズ用の短い説明（ここは“あなたの言葉”でOK）

const TERMS = [
  // ===== 1年 生命 =====
{ grade:1, field:"life", term:"えら", hint:"魚類と両生類の幼生(子)にある。" },
{ grade:1, field:"life", term:"おしべ", hint:"花粉が作られる。" },
{ grade:1, field:"life", term:"雄花・雌花", hint:"1つの花の中におしべめしべがある両性花ではなく、お…" },
{ grade:1, field:"life", term:"外とう膜", hint:"ここから石灰質の殻を分泌する。" },
{ grade:1, field:"life", term:"がく", hint:"花の内部を守っている。" },
{ grade:1, field:"life", term:"仮根", hint:"コケ植物などの根に似た組織。" },
{ grade:1, field:"life", term:"果実", hint:"成長して果実になる。" },
{ grade:1, field:"life", term:"花粉", hint:"被子植物のやく、裸子植物の花粉のうでつくられる。" },
{ grade:1, field:"life", term:"花粉のう", hint:"裸子植物の雄花にあり、中で花粉がつくられる。" },
{ grade:1, field:"life", term:"花弁", hint:"花のつくりのひとつで、めしべ、おしべのまわりにある。" },
{ grade:1, field:"life", term:"魚類", hint:"うろこでおおわれている。" },
{ grade:1, field:"life", term:"顕微鏡", hint:"非常に小さなものを拡大して観察する装置。" },
{ grade:1, field:"life", term:"恒温動物", hint:"まわりの温度が変化しても体温を一定に保つ動物。" },
{ grade:1, field:"life", term:"甲殻類", hint:"頭胸部、腹部の２つ、または頭部、胸部、腹部の3つに…" },
{ grade:1, field:"life", term:"合弁花", hint:"花弁がくっついて一つになっている花。" },
{ grade:1, field:"life", term:"合弁花類", hint:"双子葉類のうち合弁花を持つ植物。" },
{ grade:1, field:"life", term:"孔辺細胞", hint:"半月型をした細胞で、この孔辺細胞が2個向き合って、…" },
{ grade:1, field:"life", term:"コケ植物", hint:"体全体から吸収する。" },
{ grade:1, field:"life", term:"昆虫類", hint:"ねがある。" },
{ grade:1, field:"life", term:"シダ植物", hint:"茎が地中にあるものが多い。" },
{ grade:1, field:"life", term:"子房", hint:"被子植物のめしべの根もとのふくらんだ部分。" },
{ grade:1, field:"life", term:"雌雄異株", hint:"イチョウやソテツ、ホウレンソウなどがある。" },
{ grade:1, field:"life", term:"主根と側根", hint:"太い主根がまっすぐ地中に伸び、そのまわりに細い側根…" },
{ grade:1, field:"life", term:"種子", hint:"種子植物で、受粉して受精したのち胚珠が発達して種子…" },
{ grade:1, field:"life", term:"種子植物", hint:"裸子植物と被子植物に分けられる。" },
{ grade:1, field:"life", term:"受粉", hint:"成長して果実になり、胚珠は種子になる。" },
{ grade:1, field:"life", term:"セキツイ動物", hint:"虫類、鳥類、哺乳類に分類される。" },
{ grade:1, field:"life", term:"節足動物", hint:"甲殻類、昆虫類、その他クモなど外骨格で体やあしに節…" },
{ grade:1, field:"life", term:"前葉体", hint:"精子と卵を作る細胞があり、それらが受精して受精卵が…" },
{ grade:1, field:"life", term:"双眼実体顕微鏡", hint:"両目で観察できる顕微鏡。" },
{ grade:1, field:"life", term:"双子葉類", hint:"主根と側根からなり、葉脈は網状脈、茎の維管束は輪に…" },
{ grade:1, field:"life", term:"胎生", hint:"母親の体内である程度成長してから子が生まれ、母親の…" },
{ grade:1, field:"life", term:"単子葉類", hint:"ひげ根、葉脈は平行脈、茎の維管束はバラバラになって…" },
{ grade:1, field:"life", term:"単性花・両性花", hint:"単性花で、被子植物の多くは両性花だが、キュウリやカ…" },
{ grade:1, field:"life", term:"地下茎", hint:"地下で生活するようなものもあり、地下茎という。" },
{ grade:1, field:"life", term:"柱頭", hint:"めしべの先端部分を柱頭という。" },
{ grade:1, field:"life", term:"鳥類", hint:"羽毛でおおわれている。" },
{ grade:1, field:"life", term:"デンプン", hint:"水に溶ける糖に変えて師管を通って運ばれる。" },
{ grade:1, field:"life", term:"軟体動物", hint:"体が柔らかい筋肉でできていて、外とう膜につつまれて…" },
{ grade:1, field:"life", term:"根", hint:"地中にあり、表面から水や水に溶けた養分(肥料分)を…" },
{ grade:1, field:"life", term:"肺呼吸", hint:"肺によっておこなう呼吸。" },
{ grade:1, field:"life", term:"胚珠", hint:"胚珠は子房の中にあり、裸子植物では子房がないので胚…" },
{ grade:1, field:"life", term:"は虫類", hint:"こうらやうろこなどでおおわれている。" },
{ grade:1, field:"life", term:"花", hint:"種子植物で、種子植物には被子植物と裸子植物がある。" },
{ grade:1, field:"life", term:"花のつくり", hint:"被子植物裸子植物(マツ)" },
{ grade:1, field:"life", term:"葉のつきかた", hint:"どの葉にも光がよく当たるようなつき方をしている。" },
{ grade:1, field:"life", term:"ひげ根", hint:"太い根がなく多数の細いひげ根が広がっている。" },
{ grade:1, field:"life", term:"表皮", hint:"葉緑体が無い。" },
{ grade:1, field:"life", term:"風媒花・虫媒花", hint:"色鮮やかな花弁や、蜜、においなどで昆虫をひきつけ、…" },
{ grade:1, field:"life", term:"分類", hint:"似た特徴をもつものを1つのグループにまとめ,いくつ…" },
{ grade:1, field:"life", term:"平行脈", hint:"平行脈である。" },
{ grade:1, field:"life", term:"変温動物", hint:"冬眠するものが多い。" },
{ grade:1, field:"life", term:"胞子", hint:"発芽すると前葉体になり、前葉体で卵と精子がつくられ…" },
{ grade:1, field:"life", term:"胞子のう", hint:"胞子がつくられる器官。" },
{ grade:1, field:"life", term:"哺乳類", hint:"毛でおおわれている。" },
{ grade:1, field:"life", term:"無セキツイ動物", hint:"脊椎(背骨)のない動物。" },
{ grade:1, field:"life", term:"めしべ", hint:"胚珠がある。" },
{ grade:1, field:"life", term:"網状脈", hint:"網状脈である。" },
{ grade:1, field:"life", term:"やく", hint:"被子植物のおしべの先端にあり、中で花粉が作られる。" },
{ grade:1, field:"life", term:"葉脈", hint:"師管がある。" },
{ grade:1, field:"life", term:"卵生", hint:"殻がないが、陸上に生む卵には乾燥を防ぐために殻があ…" },
{ grade:1, field:"life", term:"離弁花", hint:"花弁が分かれている花のこと。" },
{ grade:1, field:"life", term:"離弁花類", hint:"双子葉類のうち離弁花をもつ植物。" },
{ grade:1, field:"life", term:"両生類", hint:"水中で生活しえら呼吸だが、成体(親)は陸上で生活し…" },
{ grade:1, field:"life", term:"ルーペ", hint:"ルーペを動かさず観察するものを前後に動かしてピント…" },
{ grade:1, field:"life", term:"外骨格", hint:"昆虫類や甲殻類など外側に殻があり、その中に筋肉があ…" },

  // ===== 1年 物質（chem扱い） =====
{ grade:1, field:"chem", term:"アルゴン", hint:"無色無臭の気体。" },
{ grade:1, field:"chem", term:"アンモニア", hint:"アンモニア水で、アルカリ性になる。" },
{ grade:1, field:"chem", term:"一酸化炭素", hint:"CO、有機物が不完全燃焼すると発生する。" },
{ grade:1, field:"chem", term:"一酸化二窒素", hint:"芳香のある無色の気体。" },
{ grade:1, field:"chem", term:"液体", hint:"基本、体積は大きくなるが粒子の数は変わらないので質量は変わらな…" },
{ grade:1, field:"chem", term:"エタノール", hint:"-115℃、沸点は78℃である。" },
{ grade:1, field:"chem", term:"塩化水素", hint:"有毒で、刺激臭のある無色の気体。" },
{ grade:1, field:"chem", term:"延性", hint:"延性が大きく、特に金,銀,銅,白金は細い線に引き伸…" },
{ grade:1, field:"chem", term:"塩素", hint:"酸性になる。" },
{ grade:1, field:"chem", term:"下方置換法", hint:"水にとけやすくて空気より重い気体を集める方法。" },
{ grade:1, field:"chem", term:"気体", hint:"変わらないが、 粒子が飛び回り粒子どうしの間隔が非…" },
{ grade:1, field:"chem", term:"金属", hint:"金属と非金属に分けることができる。" },
{ grade:1, field:"chem", term:"金属には以下の共通の性質がある", hint:"" },
{ grade:1, field:"chem", term:"金属光沢(みがくと光る)", hint:"" },
{ grade:1, field:"chem", term:"電気をよく通す", hint:"" },
{ grade:1, field:"chem", term:"熱を伝えやすい", hint:"金属共通の性質ではない(鉄など一部の金属だけ)" },
{ grade:1, field:"chem", term:"金属光沢", hint:"金属の特徴の一つ。" },
{ grade:1, field:"chem", term:"結晶", hint:"物質を形成する粒子が規則正しく並んでいる固体。" },
{ grade:1, field:"chem", term:"固体", hint:"粒子が規則的に並んで結晶となっている。" },
{ grade:1, field:"chem", term:"混合物", hint:"2種類以上の物質が混ざっているもの。" },
{ grade:1, field:"chem", term:"再結晶", hint:"温度が高い水にたくさん溶かして冷やす方法と水を蒸発…" },
{ grade:1, field:"chem", term:"酸素", hint:"わずかしかとけない。" },
{ grade:1, field:"chem", term:"質量パーセント濃度", hint:"水溶液の濃さを表す。" },
{ grade:1, field:"chem", term:"純粋な物質", hint:"他の物質が混じっていない、1種類の物質でできている…" },
{ grade:1, field:"chem", term:"硝酸カリウム", hint:"硝石として産出する。" },
{ grade:1, field:"chem", term:"状態変化", hint:"あたためたり、冷やしたりすることで固体、液体、気体…" },
{ grade:1, field:"chem", term:"上方置換法", hint:"水にとけやすくて空気より軽い気体を集める方法。" },
{ grade:1, field:"chem", term:"蒸留", hint:"沸点の低いエタノールを多く含む気体が出てくる、後に…" },
{ grade:1, field:"chem", term:"食塩", hint:"801℃、沸点は1485℃、結晶は立方体である。" },
{ grade:1, field:"chem", term:"ショ糖", hint:"スクロースともいう。" },
{ grade:1, field:"chem", term:"水上置換法", hint:"水にとけにくい気体を集める方法。" },
{ grade:1, field:"chem", term:"水素", hint:"H、水素分子の化学式はH2。" },
{ grade:1, field:"chem", term:"水溶液", hint:"透明で、濃さはどこも同じであり、放置しても一部分が…" },
{ grade:1, field:"chem", term:"窒素", hint:"N、窒素分子の化学式はN2 窒素はふつうの温度では…" },
{ grade:1, field:"chem", term:"展性", hint:"この性質が大きく、箔(はく)に加工される。" },
{ grade:1, field:"chem", term:"ドライアイス", hint:"固体から直接気体に状態変化する(昇華)。" },
{ grade:1, field:"chem", term:"二酸化硫黄", hint:"有毒で無色な刺激臭のある気体。" },
{ grade:1, field:"chem", term:"二酸化炭素", hint:"炭酸水といい、酸性になる。" },
{ grade:1, field:"chem", term:"二酸化窒素", hint:"有毒な赤褐色の気体。" },
{ grade:1, field:"chem", term:"ネオン", hint:"無色無臭の気体。" },
{ grade:1, field:"chem", term:"非金属", hint:"金属以外の物質を非金属という。" },
{ grade:1, field:"chem", term:"ガラス、プラスチック、水など", hint:"" },
{ grade:1, field:"chem", term:"物質", hint:"ものをその材料に着目して区別する場合物質という。" },
{ grade:1, field:"chem", term:"物体", hint:"ものを外観や、使用目的で区別する場合物体という。" },
{ grade:1, field:"chem", term:"沸点", hint:"加熱を続けても温度は一定である。" },
{ grade:1, field:"chem", term:"プラスチック", hint:"合成樹脂とも呼ばれ、石油を精製して得られるナフサを…" },
{ grade:1, field:"chem", term:"プロパン", hint:"無色無臭の気体。" },
{ grade:1, field:"chem", term:"ヘリウム", hint:"超低温を必要とする機器や実験などで使われる。" },
{ grade:1, field:"chem", term:"飽和水溶液", hint:"溶けなくなる。" },
{ grade:1, field:"chem", term:"密度", hint:"体積1cm3あたりの質量。" },
{ grade:1, field:"chem", term:"無機物", hint:"有機物以外の物質。" },
{ grade:1, field:"chem", term:"食塩、水、二酸化炭素、金属など", hint:"炭素を含んでいるが無機物である。" },
{ grade:1, field:"chem", term:"メタン", hint:"無色無臭の気体で、水に溶けにくく空気より軽いので水…" },
{ grade:1, field:"chem", term:"有機物", hint:"炭素と共に水素を含むものが多く、燃やすと炭素が酸素…" },
{ grade:1, field:"chem", term:"融点", hint:"物質の種類によって決まっている。" },
{ grade:1, field:"chem", term:"溶液", hint:"溶質を溶媒にとかしたもの" },
{ grade:1, field:"chem", term:"溶解度", hint:"物質によって異なり、温度によって変化する。" },
{ grade:1, field:"chem", term:"溶解度曲線", hint:"水の温度と溶解度の関係を表したグラフを溶解度曲線と…" },
{ grade:1, field:"chem", term:"溶質", hint:"個体、液体に気体を溶かした場合、溶質は気体である。" },
{ grade:1, field:"chem", term:"溶媒", hint:"水溶液といい、溶媒がアルコールならアルコール溶液で…" },
{ grade:1, field:"chem", term:"硫化水素", hint:"有毒で特有のにおい(腐卵臭)がある、無色の気体。" },
{ grade:1, field:"chem", term:"ろ過", hint:"ガラス棒につたわせ、ろうとの足をビーカーの壁に沿わ…" },



  // ===== 1年 エネルギー（phys） =====
  { grade: 1, field: "phys", term: "光の反射", hint: "光が物体に当たり、はね返ること。" },
  { grade: 1, field: "phys", term: "入射角", hint: "入ってくる光と法線がつくる角。" },
  { grade: 1, field: "phys", term: "反射角", hint: "反射した光と法線がつくる角。" },
  { grade: 1, field: "phys", term: "凸レンズ", hint: "中央がふくらみ、光を集めるレンズ。" },
  { grade: 1, field: "phys", term: "焦点", hint: "平行光が集まる点（レンズの場合）。" },
  { grade: 1, field: "phys", term: "実像", hint: "スクリーンに映せる像。" },
  { grade: 1, field: "phys", term: "音", hint: "物体の振動が伝わって感じるもの。" },
  { grade: 1, field: "phys", term: "振幅", hint: "振動のふれの大きさ。" },
  { grade: 1, field: "phys", term: "振動数", hint: "1秒間の振動の回数（Hz）。" },
  { grade: 1, field: "phys", term: "力", hint: "物体の運動のようすを変えるはたらき。" },
  { grade: 1, field: "phys", term: "ばねばかり", hint: "力の大きさを測る器具（N）。" },
  { grade: 1, field: "phys", term: "作用・反作用", hint: "力は必ず対になってはたらく。" },
  { grade: 1, field: "phys", term: "力の合成", hint: "2つ以上の力を1つの力として表すこと。" },
  { grade: 1, field: "phys", term: "力の分解", hint: "1つの力を成分に分けて考えること。" },

  // ===== 1年 地球（earth） =====
  { grade: 1, field: "earth", term: "火山", hint: "地下のマグマが地表に出る現象が起こる場所。" },
  { grade: 1, field: "earth", term: "マグマ", hint: "高温でどろどろの岩石（地下）。" },
  { grade: 1, field: "earth", term: "溶岩", hint: "地表に出たマグマ。" },
  { grade: 1, field: "earth", term: "火山灰", hint: "細かい火山噴出物。" },
  { grade: 1, field: "earth", term: "地震", hint: "地面がゆれる現象。" },
  { grade: 1, field: "earth", term: "震源", hint: "地震が起こり始めた地下の場所。" },
  { grade: 1, field: "earth", term: "震央", hint: "震源の真上の地表の地点。" },
  { grade: 1, field: "earth", term: "P波", hint: "最初に伝わる、たて波のゆれ。" },
  { grade: 1, field: "earth", term: "S波", hint: "あとから伝わる、横波のゆれ。" },
  { grade: 1, field: "earth", term: "地層", hint: "地面の下に重なっている層。" },
  { grade: 1, field: "earth", term: "化石", hint: "昔の生物の体や生活の跡が地層に残ったもの。" },

  // ===== 2年 化学 =====
  { grade: 2, field: "chem", term: "原子", hint: "物質をつくる最小の粒の1つの考え方。" },
  { grade: 2, field: "chem", term: "分子", hint: "原子が結びついた粒。" },
  { grade: 2, field: "chem", term: "化学式", hint: "物質を原子記号で表した式。" },
  { grade: 2, field: "chem", term: "化学反応式", hint: "反応物と生成物を式で表したもの。" },
  { grade: 2, field: "chem", term: "化学変化", hint: "別の物質ができる変化。" },
  { grade: 2, field: "chem", term: "質量保存の法則", hint: "反応の前後で物質全体の質量は変わらない。" },
  { grade: 2, field: "chem", term: "酸化", hint: "物質が酸素と結びつく反応のことが多い。" },
  { grade: 2, field: "chem", term: "還元", hint: "酸化物から酸素がうばわれる変化など。" },
  { grade: 2, field: "chem", term: "熱分解", hint: "加熱して別の物質に分かれる反応。" },
  { grade: 2, field: "chem", term: "電気分解", hint: "電流で分解して別の物質を得る反応。" },

  // ===== 2年 生命 =====
  { grade: 2, field: "life", term: "光合成", hint: "光を受けて二酸化炭素と水から養分をつくるはたらき。" },
  { grade: 2, field: "life", term: "呼吸", hint: "養分を分解してエネルギーを取り出すはたらき。" },
  { grade: 2, field: "life", term: "消化", hint: "食べ物を小さな物質に分解すること。" },
  { grade: 2, field: "life", term: "吸収", hint: "消化された養分が体内に取り込まれること。" },
  { grade: 2, field: "life", term: "血液", hint: "酸素や養分などを運ぶ体液。" },
  { grade: 2, field: "life", term: "心臓", hint: "血液を全身へ送り出すポンプの役割。" },
  { grade: 2, field: "life", term: "肺", hint: "酸素と二酸化炭素を交換する器官。" },
  { grade: 2, field: "life", term: "小腸", hint: "消化と吸収が進む器官。" },
  { grade: 2, field: "life", term: "大腸", hint: "水分を吸収し、便をつくる器官。" },
  { grade: 2, field: "life", term: "感覚器官", hint: "光・音・においなどを感じ取る器官。" },
  { grade: 2, field: "life", term: "刺激と反応", hint: "刺激を受けて体が変化・行動するしくみ。" },

  // ===== 2年 地球（天気） =====
  { grade: 2, field: "earth", term: "気圧", hint: "空気が押す力のはたらき。" },
  { grade: 2, field: "earth", term: "湿度", hint: "空気中の水蒸気の“しめり具合”の割合。" },
  { grade: 2, field: "earth", term: "露点", hint: "空気を冷やして水滴が生じ始める温度。" },
  { grade: 2, field: "earth", term: "飽和水蒸気量", hint: "空気がふくめる水蒸気の最大量（温度で変わる）。" },
  { grade: 2, field: "earth", term: "雲", hint: "小さな水滴や氷の粒が集まったもの。" },
  { grade: 2, field: "earth", term: "前線", hint: "性質の異なる気団が接する境目。" },
  { grade: 2, field: "earth", term: "低気圧", hint: "周りより気圧が低い所。上昇気流が起こりやすい。" },
  { grade: 2, field: "earth", term: "高気圧", hint: "周りより気圧が高い所。下降気流が起こりやすい。" },

  // ===== 2年 物理（電気） =====
  { grade: 2, field: "phys", term: "電流", hint: "電気の流れ。単位はA（アンペア）。" },
  { grade: 2, field: "phys", term: "電圧", hint: "電流を流そうとするはたらき。単位はV（ボルト）。" },
  { grade: 2, field: "phys", term: "抵抗", hint: "電流の流れにくさ。単位はΩ（オーム）。" },
  { grade: 2, field: "phys", term: "オームの法則", hint: "電圧・電流・抵抗の関係（V=IR）。" },
  { grade: 2, field: "phys", term: "直列回路", hint: "電流の通り道が1本の回路。" },
  { grade: 2, field: "phys", term: "並列回路", hint: "電流の通り道が分かれる回路。" },
  { grade: 2, field: "phys", term: "電力", hint: "電気の仕事の速さ。単位はW（ワット）。" },
  { grade: 2, field: "phys", term: "磁界", hint: "磁石の力がはたらく空間。" },
  { grade: 2, field: "phys", term: "電磁誘導", hint: "磁界の変化で電流が生じる現象。" },

  // ===== 3年 生命（遺伝） =====
  { grade: 3, field: "life", term: "無性生殖", hint: "親1個体からふえる。遺伝情報は同じになりやすい。" },
  { grade: 3, field: "life", term: "有性生殖", hint: "卵と精子などが関わってふえる。" },
  { grade: 3, field: "life", term: "減数分裂", hint: "生殖細胞ができるときの特別な細胞分裂。" },
  { grade: 3, field: "life", term: "遺伝", hint: "親の性質が子に受け継がれること。" },
  { grade: 3, field: "life", term: "DNA", hint: "遺伝情報をもつ物質。" },
  { grade: 3, field: "life", term: "染色体", hint: "DNAを含む、遺伝情報のかたまり。" },
  { grade: 3, field: "life", term: "対立形質", hint: "同じ性質のちがい（例：丸い/しわ）。" },
  { grade: 3, field: "life", term: "顕性", hint: "表れやすい性質（優性）。" },
  { grade: 3, field: "life", term: "潜性", hint: "表れにくい性質（劣性）。" },
  { grade: 3, field: "life", term: "分離の法則", hint: "対立形質が次世代に分かれて現れるという規則。" },
  { grade: 3, field: "life", term: "クローン", hint: "遺伝情報が同じ個体（または細胞）をつくること。" },

  // ===== 3年 化学（イオン） =====
  { grade: 3, field: "chem", term: "イオン", hint: "電気を帯びた原子や分子。" },
  { grade: 3, field: "chem", term: "陽イオン", hint: "＋の電気を帯びたイオン。" },
  { grade: 3, field: "chem", term: "陰イオン", hint: "−の電気を帯びたイオン。" },
  { grade: 3, field: "chem", term: "電解質", hint: "水溶液が電気を通す物質。" },
  { grade: 3, field: "chem", term: "非電解質", hint: "水溶液が電気を通しにくい物質。" },
  { grade: 3, field: "chem", term: "酸", hint: "水溶液中で水素イオンを出す性質（中学的定義）。" },
  { grade: 3, field: "chem", term: "アルカリ", hint: "水溶液中で水酸化物イオンを出す性質（中学的定義）。" },
  { grade: 3, field: "chem", term: "中和", hint: "酸とアルカリが反応して性質が打ち消し合うこと。" },
  { grade: 3, field: "chem", term: "指示薬", hint: "液性によって色が変わる薬品。" },
  { grade: 3, field: "chem", term: "水素イオン", hint: "酸の性質に関わる＋のイオン。" },
  { grade: 3, field: "chem", term: "水酸化物イオン", hint: "アルカリの性質に関わる−のイオン。" },
  { grade: 3, field: "chem", term: "電池", hint: "化学変化で電流を取り出すしくみ。" },

  // ===== 3年 物理（運動とエネルギー） =====
  { grade: 3, field: "phys", term: "仕事", hint: "力が物体を動かしたときの量（力×距離）。" },
  { grade: 3, field: "phys", term: "仕事率", hint: "一定時間あたりの仕事（速さ）。" },
  { grade: 3, field: "phys", term: "運動エネルギー", hint: "運動している物体がもつエネルギー。" },
  { grade: 3, field: "phys", term: "位置エネルギー", hint: "高い所など、位置によってもつエネルギー。" },
  { grade: 3, field: "phys", term: "エネルギー保存", hint: "形を変えてもエネルギー全体は一定とみなす考え。" },
  { grade: 3, field: "phys", term: "慣性", hint: "運動の状態を保とうとする性質。" },
  { grade: 3, field: "phys", term: "速さ", hint: "一定時間に進む距離。" },
  { grade: 3, field: "phys", term: "加速度", hint: "速さの変化の割合（中学では感覚的に扱うことが多い）。" },
  { grade: 3, field: "phys", term: "水圧", hint: "水が押す力。深いほど大きい。" },
  { grade: 3, field: "phys", term: "浮力", hint: "水中で物体が受ける上向きの力。" },

  // ===== 3年 地球（宇宙） =====
  { grade: 3, field: "earth", term: "日周運動", hint: "1日の中で天体が動いて見えるようす。" },
  { grade: 3, field: "earth", term: "年周運動", hint: "1年の中で星座などが変化して見えるようす。" },
  { grade: 3, field: "earth", term: "地軸", hint: "地球が自転するときの回転の軸。" },
  { grade: 3, field: "earth", term: "自転", hint: "地球が1日に1回回転すること。" },
  { grade: 3, field: "earth", term: "公転", hint: "地球が太陽の周りを1年で回ること。" },
  { grade: 3, field: "earth", term: "月の満ち欠け", hint: "太陽光の当たり方で、月の見え方が変わること。" },
  { grade: 3, field: "earth", term: "太陽系", hint: "太陽とその周りを回る天体の集まり。" },
  { grade: 3, field: "earth", term: "銀河系", hint: "多数の恒星が集まった“天の川銀河”のこと。" },
];
